# Generated by Django 3.1.4 on 2021-03-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210308_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='telefon'),
        ),
    ]
