# Generated by Django 3.1.4 on 2021-03-09 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210308_1958'),
        ('order', '0004_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='num_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='num_title',
            field=models.CharField(choices=[('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077'), ('099', '099')], default='', max_length=10, verbose_name='num title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='surname',
            field=models.CharField(default='', max_length=50, verbose_name='surname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='tel_number',
            field=models.CharField(default='', error_messages={'required': 'Mobil nomre 7 reqemli olmalidir'}, max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='telefon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
