<<<<<<< HEAD:amdtelecom/order/migrations/0007_auto_20210311_1721.py
# Generated by Django 3.1.4 on 2021-03-11 13:21
=======
# Generated by Django 3.1.4 on 2021-03-11 13:29
>>>>>>> c317aee09938b15c7386679b162e8229b5868cf3:amdtelecom/order/migrations/0006_auto_20210311_1729.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD:amdtelecom/order/migrations/0007_auto_20210311_1721.py
        ('order', '0006_checkout_order'),
=======
        ('order', '0005_auto_20210309_2044'),
>>>>>>> c317aee09938b15c7386679b162e8229b5868cf3:amdtelecom/order/migrations/0006_auto_20210311_1729.py
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
<<<<<<< HEAD:amdtelecom/order/migrations/0007_auto_20210311_1721.py
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
=======
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
>>>>>>> c317aee09938b15c7386679b162e8229b5868cf3:amdtelecom/order/migrations/0006_auto_20210311_1729.py
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='surname'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefon'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='telefon'),
        ),
    ]
