# Generated by Django 3.1.4 on 2021-03-11 13:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210309_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='order',
            name='num_title',
            field=models.CharField(blank=True, choices=[('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077'), ('099', '099')], max_length=10, null=True, verbose_name='num title'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='surname'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel_number',
            field=models.CharField(blank=True, error_messages={'required': 'Mobil nomre 7 reqemli olmalidir'}, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='telefon'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='telefon'),
        ),
    ]
