# Generated by Django 3.1.4 on 2021-03-13 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210311_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tel_number',
            field=models.CharField(blank=True, error_messages={'required': 'Mobil nomre 10 reqemli olmalidir'}, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='telefon'),
        ),
    ]
