# Generated by Django 3.1.4 on 2021-03-11 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='order',
            name='num_title',
            field=models.CharField(blank=True, choices=[('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077'), ('099', '099')], max_length=10, null=True, verbose_name='num title'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='surname'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel_number',
            field=models.CharField(blank=True, error_messages={'required': 'Mobil nomre 7 reqemli olmalidir'}, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='telefon'),
        ),
    ]
