# Generated by Django 3.1.4 on 2021-03-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='surname'),
        ),
        migrations.AddField(
            model_name='order',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='telefon'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
