# Generated by Django 3.1.4 on 2021-03-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_checkout_order'),
        ('order', '0003_auto_20210309_2051'),
    ]

    operations = [
    ]
