# Generated by Django 3.1.4 on 2021-02-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='categories_images', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(default='', editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('is_main', models.BooleanField(default=False, verbose_name='is_main')),
                ('is_second', models.BooleanField(default=False, verbose_name='is_second')),
                ('is_third', models.BooleanField(default=False, verbose_name='is_third')),
                ('status', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='_category_parent_+', to='product.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'ordering': ('-created_at', 'title'),
                'unique_together': {('slug',)},
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('image', models.ImageField(blank=True, upload_to='marka_images', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(default='', editable=False, max_length=110, unique=True, verbose_name='Slug')),
                ('status', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markas',
                'db_table': 'marka',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color Name')),
                ('color_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color code')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(db_index=True, max_length=50, verbose_name='SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sale_count', models.IntegerField(default=0, verbose_name='Sale Count')),
                ('is_new', models.BooleanField(default=True, verbose_name='is_new')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
                ('is_discount', models.BooleanField(default=False, verbose_name='is_discount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('discount_type', models.PositiveIntegerField(choices=[(1, 'Not'), (2, 'Percent'), (3, 'Unit')], default=1, verbose_name='Discount Type')),
                ('discount_value', models.IntegerField(blank=True, null=True, verbose_name='Discount Value')),
                ('status', models.BooleanField(default=True, verbose_name='is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product.category')),
                ('marka', models.ManyToManyField(related_name='marka', to='product.Marka')),
                ('same_product', models.ManyToManyField(blank=True, related_name='_product_same_product_+', to='product.Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default='Not', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
            options={
                'verbose_name': 'Product details',
                'verbose_name_plural': 'Products details',
                'db_table': 'Product details',
            },
        ),
        migrations.CreateModel(
            name='Product_details_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product_details')),
            ],
            options={
                'verbose_name': 'Product property',
                'verbose_name_plural': 'Products properties',
                'db_table': 'Product property',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tag',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Image')),
                ('is_second_main', models.BooleanField(default=False, verbose_name='Second Main Image')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product_details_property_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='Content')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_details_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details_properties', to='product.product_details_property')),
            ],
            options={
                'verbose_name': 'Property name',
                'verbose_name_plural': 'Properties names',
                'db_table': 'Property name',
            },
        ),
        migrations.CreateModel(
            name='Product_colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.product')),
            ],
            options={
                'verbose_name': 'Product color',
                'verbose_name_plural': 'Product colors',
                'db_table': 'Product colors',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='product.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to='account.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('title', 'slug')},
        ),
    ]
