# Generated by Django 3.1.4 on 2021-02-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details_property_name',
            old_name='content',
            new_name='title',
        ),
    ]
