# Generated by Django 3.1.4 on 2021-02-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210219_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details_property',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_details_property_name',
            name='product_details_property',
        ),
        migrations.AddField(
            model_name='product_details',
            name='Product_details_property_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_details_property_name', to='product.product_details_property_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_details_property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_details_properties', to='product.product_details_property'),
            preserve_default=False,
        ),
    ]
