# Generated by Django 3.1.2 on 2020-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201019_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
