# Generated by Django 3.1.4 on 2021-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0003_auto_20210219_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.ManyToManyField(blank=True, null=True, related_name='marka', to='product.Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='same_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='_product_same_product_+', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product.Tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='who_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_products', to='account.Customer'),
        ),
    ]
