# Generated by Django 3.1.2 on 2020-10-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201020_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('video', models.CharField(blank=True, max_length=200)),
                ('internal_storage', models.CharField(blank=True, max_length=50)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('production_year', models.CharField(blank=True, max_length=50)),
                ('sim_count', models.CharField(blank=True, max_length=50)),
                ('sim_type', models.CharField(blank=True, max_length=50)),
                ('operation_system', models.CharField(blank=True, max_length=100)),
                ('operation_system_version', models.CharField(blank=True, max_length=100)),
                ('screen_size', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(blank=True, max_length=50)),
                ('back_camera', models.CharField(blank=True, max_length=50)),
                ('front_camera', models.CharField(blank=True, max_length=50)),
                ('battery', models.CharField(blank=True, max_length=50)),
                ('weigth', models.CharField(blank=True, max_length=50)),
                ('prosessor', models.CharField(blank=True, max_length=50)),
                ('security', models.CharField(blank=True, max_length=50)),
                ('guarantee', models.CharField(blank=True, max_length=50)),
                ('operator_prefix', models.CharField(blank=True, max_length=50)),
                ('wifi', models.BooleanField(blank=True)),
                ('allow_3G', models.BooleanField(blank=True)),
                ('allow_4G', models.BooleanField(blank=True)),
                ('nfc', models.BooleanField(blank=True)),
                ('gps', models.BooleanField(blank=True)),
                ('eye_recognition', models.BooleanField(blank=True)),
                ('waterproof', models.BooleanField(blank=True)),
                ('faceID', models.BooleanField(blank=True)),
                ('shockproof', models.BooleanField(blank=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
