# Generated by Django 3.1.4 on 2021-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210308_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='content',
            field=models.CharField(default=2, max_length=50, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
