# Generated by Django 3.1.4 on 2021-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0004_auto_20210219_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.ManyToManyField(blank=True, related_name='marka', to='product.Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='liked_products', to='account.Customer'),
        ),
    ]
