# Generated by Django 3.1.4 on 2021-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_details_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Value'),
        ),
    ]
