# Generated by Django 3.1.4 on 2021-02-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210218_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created_at', 'title'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
