# Generated by Django 3.1.4 on 2021-02-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210219_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='same_product',
            field=models.ManyToManyField(blank=True, related_name='_product_same_product_+', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.Tag'),
        ),
    ]
