# Generated by Django 3.1.4 on 2021-03-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_details_product_details_propert_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_details_property_name',
            options={'verbose_name': 'Detail name', 'verbose_name_plural': 'Details names'},
        ),
        migrations.AlterModelTable(
            name='product_details_property_name',
            table='Detail name ',
        ),
    ]
