# Generated by Django 3.1.4 on 2021-03-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210309_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Daxili yaddaş'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM'),
        ),
    ]
