# Generated by Django 3.1.2 on 2020-10-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201024_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='product_id',
            new_name='product',
        ),
    ]
