# Generated by Django 3.1.4 on 2021-03-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210310_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Operativ yaddaş'),
        ),
    ]
