# Generated by Django 3.1.4 on 2021-03-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210310_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Daxili yaddaş'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Operativ yaddaş'),
        ),
    ]
