# Generated by Django 3.1.4 on 2021-02-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details_property_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Content')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detail property value',
                'verbose_name_plural': 'Details properties values',
                'db_table': 'Detail property value',
            },
        ),
        migrations.AlterModelOptions(
            name='product_details_property_name',
            options={'verbose_name': 'Detail property key', 'verbose_name_plural': 'Details properties keys'},
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_details_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details_properties', to='product.product_details_property_name'),
        ),
        migrations.AlterField(
            model_name='product_details_property_name',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterModelTable(
            name='product_details_property_name',
            table='Detail property key',
        ),
        migrations.DeleteModel(
            name='Product_details_property',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='Product_details_property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details_property_name', to='product.product_details_property_value'),
        ),
    ]
