# Generated by Django 3.1.2 on 2020-10-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='product_id',
            new_name='product',
        ),
    ]
