# Generated by Django 3.1.4 on 2021-02-20 17:51

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210220_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorful.fields.RGBColorField(default=''),
            preserve_default=False,
        ),
    ]
