# Generated by Django 3.1.4 on 2021-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210310_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
