# Generated by Django 3.1.4 on 2021-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_published_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_expiration',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
