# Generated by Django 3.1.4 on 2021-02-20 18:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_c',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
    ]
