# Generated by Django 3.1.2 on 2020-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201026_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='external_storage',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
