# Generated by Django 3.1.4 on 2021-03-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210311_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_storage',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Daxili yaddaş'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_expiration',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
