# Generated by Django 3.1.4 on 2021-02-20 18:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_color_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='color_c',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18),
        ),
    ]
