# Generated by Django 3.1.4 on 2021-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210228_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='operator_code',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Operator'),
        ),
    ]
