# Generated by Django 3.1.4 on 2021-02-20 18:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210220_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_c',
        ),
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18, verbose_name='Color code'),
        ),
    ]
