# Generated by Django 3.1.2 on 2020-10-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20201029_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='color',
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
    ]
