# Generated by Django 3.1.4 on 2021-03-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_operator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operator_code',
            field=models.PositiveSmallIntegerField(blank=True, max_length=3, null=True, verbose_name='Operator'),
        ),
    ]
