# Generated by Django 3.1.2 on 2020-10-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201031_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
