# Generated by Django 3.1.4 on 2021-03-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210301_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operator_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Operator code'),
        ),
    ]
