# Generated by Django 3.1.4 on 2021-02-22 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210220_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product property',
                'verbose_name_plural': 'Products properties',
                'db_table': 'Product property',
            },
        ),
        migrations.AlterModelOptions(
            name='product_details_property_name',
            options={'verbose_name': 'Property name', 'verbose_name_plural': 'Properties names'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color code'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='Product_details_property_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details_property_name', to='product.product_details_property_name'),
        ),
        migrations.AlterField(
            model_name='product_details_property_name',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Content'),
        ),
        migrations.AlterModelTable(
            name='product_details_property_name',
            table='Property name',
        ),
        migrations.DeleteModel(
            name='Product_details_property_value',
        ),
        migrations.AlterField(
            model_name='product_details',
            name='product_details_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details_properties', to='product.product_details_property'),
        ),
    ]
