# Generated by Django 3.1.4 on 2021-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210222_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_details_property',
            new_name='Product_details_property_value',
        ),
        migrations.AlterModelOptions(
            name='product_details_property_value',
            options={'verbose_name': 'Property value', 'verbose_name_plural': 'Properties values'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=110, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterModelTable(
            name='product_details_property_value',
            table='Property value ',
        ),
    ]
