# Generated by Django 3.1.2 on 2020-10-31 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_color_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_pro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.color_p'),
        ),
    ]
