# Generated by Django 3.1.4 on 2021-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210301_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operator_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Operator code'),
        ),
    ]
