# Generated by Django 3.1.2 on 2020-11-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_color_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_old',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
