# Generated by Django 3.1.2 on 2020-11-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20201104_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
