# Generated by Django 3.1.4 on 2021-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210301_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=110, unique=True, verbose_name='Slug'),
        ),
    ]
