# Generated by Django 3.1.4 on 2021-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210304_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operator_code',
            field=models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name='Operator code'),
        ),
    ]
